using docker for a  Node.js version usage
azilRababe/Zenova pull request #2
Opened 2023-07-20 20:02 UTC by Belaid-ALAHIAN

2023-07-21 12:09 UTC, azilRababe commented on frontend/Dockerfile
> +FROM node:12.4.0-alpine
Please update the Node.js version to **v18.15.0**
to match the project's requirements

2023-07-21 12:29 UTC, azilRababe commented on backend/Dockerfile
> +FROM node:12.4.0-alpine
**v18.15.0**

2023-07-21 12:53 UTC, azilRababe requested changes
Great work on the pull request! Everything looks good to me, except for the **Node.js version**. Could you please update it to the latest LTS version in both the frontend and backend Dockerfile files? Thank you for your valuable contribution!

2023-07-22 17:37 UTC, Belaid-ALAHIAN commented on backend/Dockerfile
> +FROM node:12.4.0-alpine
The reason why I used Docker is that when I cloned the project and tried to run "npm install," I encountered issues with installing the dependencies.
`npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amazona@1.0.0',
npm WARN EBADENGINE   required: { node: '12.4.0', npm: '6.9.0' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '9.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated multer@1.4.4: Multer 1.x is affected by CVE-2022-24434. This is fixed in v1.4.4-lts.1 which drops support for versions of Node.js before 6. Please upgrade to at least Node.js 6 and version 1.4.4-lts.1 of Multer. If you need support for older versions of Node.js, we are open to accepting patches that would fix the CVE on the main 1.x release line, whilst maintaining compatibility with Node.js 0.10.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 583 packages, and audited 584 packages in 1m

91 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (3 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.`

This problem arose because I have Node.js version 18 installed on my laptop, when i checked package.json file  I noticed that it requires Node.js version 12.4.0.

2023-07-22 23:30 UTC, azilRababe commented on backend/Dockerfile
> +FROM node:12.4.0-alpine
the project's codebase has been updated to Node.js version 18 and I've thoroughly tested the code to ensure everything runs smoothly.

try to re-run the code and If you encounter any issues or have questions, feel free to reach out.

2023-07-25 06:29 UTC, azilRababe commented
I had to close the PR due to the conflicts mentioned above. Please try to make the necessary changes and create a new PR. I'll be happy to merge it.

2023-07-25 06:29 UTC, closed without merging